is_nextjs: 0
ai_provider: openai
api_key: k
claude_model: claude-3-haiku-20240307
openai_model: gpt-4o-mini
groq_model: llama-3.1-70b-versatile
fireworks_model: accounts/fireworks/models/firefunction-v2
nebius_model: meta-llama/Llama-3.3-70B-Instruct-fast
image_generator: placeholder
pexels_api_key: ''
unsplash_api_key: ''
tavily_api_key: ''
